imu:
  add_noise: false
  gyro:
    bias_stability: 4.6
    tau: 500
    arw: 4.5
  accel:
    bias_stability: 36.0
    tau: 800
    arw: 3.6
  min_sample_time: 0.000
img:
  add_noise: false
  gaussian_noise: 80
  sap:
    add_noise: false
    prob: 0.05
