imu:
  add_noise: true
  gyro:
    bias_stability: 4.6
    tau: 500
    arw: 0.3
  accel:
    bias_stability: 36.0
    tau: 800
    arw: 0.24
  min_sample_time: 0.000
img:
  add_noise: false
  gaussian_noise: 30
